공고 작성 페이지 퍼블리싱 2차 완료 및 웹 에디터 적용
function-implementation-only/Frontend pull request #90
Opened 2023-01-12 08:01 UTC by dudwns0921

## PR 타입(하나 이상의 PR 타입을 선택해주세요)
- [ ] 버그 수정
- [ ] 기능 추가
- [ ] 리팩토링
- [ ] 기타

## 변경 사항
- 디자인에 따라 공고 작성 페이지 퍼블리싱 완료
- 내용 작성 부분에 웹 에디터 적용

## 기타 사항
- 현재 세부적인 css 적용이나 컴포넌트화 등 리팩토링이 필요합니다. 다만 작업 단위가 너무 커져 먼저 PR 합니다.
![image](https://user-images.githubusercontent.com/83502672/212010645-2ce6e652-ff19-45d1-a39c-91c8006536c4.png)

## Issue 업데이트
closes #88 
closes #80

2023-01-12 13:01 UTC, Kyungseo-Park requested changes

2023-01-12 13:01 UTC, Kyungseo-Park commented on src/store/features/tag/tagSlice.ts
>  export default tagSlice.reducer
```
export const { push, splice } = tagSlice.actions
```

위가 아래처럼 바뀌었는데 
```
export const { pushTag, spliceTag } = tagSlice.actions
```

src/components/CheckBoxComponent.tsx 파일도 수정해 주셔야 할 것 같아요

2023-01-12 13:01 UTC, Kyungseo-Park commented
src/stories/Modal.tsx 파일에 있는 


import Portal from '../presentation/components/Portal' 부분도

import Portal from '../components/Portal' 으로 변경 부탁드립니다.

2023-01-12 13:02 UTC, Kyungseo-Park commented
src/stories/PostCard.stories.tsx 파일에 있는 

```
import PostCardComponent from '../presentation/components/PostCardComponent'
```
도

```
import PostCardComponent from '../components/PostCardComponent'
```
으로 변경 부탁드립니다

2023-01-12 13:09 UTC, Kyungseo-Park commented
src/components/account/AccountModal.tsx 파일의 
```
import closeBtnImg from 'img/CloseBtn.svg'
```

도 CloseBtn.svg -> closeBtn.svg 수정 부탁드립니다.

2023-01-13 01:31 UTC, dudwns0921 commented on src/pages/Post/PostPage.tsx
> +import { Editor } from '@toast-ui/react-editor'
넵 확인입니다. 다만 Finn님이랑
1. html 문자열 통째로 전송
2. s3에 저장
3. html 문자열 그대로 반환

이런 식으로 진행을 해보기로 해서, 일단 이 방법도 해보고 이후 성능 개선을 위해 적용시키도록 하겠습니다.

2023-01-13 01:32 UTC, dudwns0921 commented on src/store/features/tag/tagSlice.ts
>  export default tagSlice.reducer
넵 확인입니다.

2023-01-13 02:02 UTC, merged